global:
  scrape_interval: 30s
  scrape_timeout: 15s
scrape_configs:
  - job_name: scrapping_recommendations_app
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets: 
      - fastapi_app:1702 