stages:
  get_data:
    cmd: python scripts/get_data.py
    deps:
      - scripts/get_data.py
    params:
      - index_col
    outs:
      - data/initial_data.csv
  fit_model:
    cmd: python scripts/fit.py
    deps:
      - data/initial_data.csv
      - scripts/fit.py
    params:
      - target_col
      - one_hot_drop
      - loss_function
    outs:
      - models/fitted_model.pkl
  evaluate_model:
    cmd: python scripts/evaluate.py
    deps:
      - models/fitted_model.pkl
      - scripts/evaluate.py
    params:
      - target_col
      - n_splits
      - n_jobs
      - metrics
    outs:
      - cv_results/cv_res.json 