export $(cat ../.env | xargs)
export MLFLOW_S3_ENDPOINT_URL=$MLFLOW_S3_ENDPOINT_URL
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
export AWS_BACKET_NAME=$S3_BUCKET_NAME
export DESTINATION_USER=$DB_DESTINATION_USER
export DESTINATION_PASSWORD=$DB_DESTINATION_PASSWORD
export DESTINATION_HOST=$DB_DESTINATION_HOST
export DESTINATION_PORT=$DB_DESTINATION_PORT
export DESTINATION_NAME=$DB_DESTINATION_NAME


mlflow server \
  --backend-store-uri postgresql://$DESTINATION_USER:$DESTINATION_PASSWORD@$DESTINATION_HOST:$DESTINATION_PORT/$DESTINATION_NAME\
    --default-artifact-root s3://$AWS_BACKET_NAME\
    --registry-store-uri postgresql://$DESTINATION_USER:$DESTINATION_PASSWORD@$DESTINATION_HOST:$DESTINATION_PORT/$DESTINATION_NAME\
    --no-serve-artifacts 
