{
 "title": "Price predict app",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Изменение количества корректных и некорректных запросов к модели в минуту",
   "type": "timeseries",
   "description": "rate(http_request_fails_counter_total[1m]) & rate(app_predictions_count{}[1m])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_fails_counter_total[1m])",
     "legendFormat": "{{fails requests rate}}"
    },
    {
     "expr": "rate(app_predictions_count{}[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Количество запросов к модели за последние 3 минуты, в зависимости от предсказанной цены",
   "type": "timeseries",
   "description": "increase(app_predictions_bucket{le=\"....\"}[3m])",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(app_predictions_bucket{le=\"2e+06\"}[3m])",
     "legendFormat": "{le = 2e6}"
    },
    {
     "expr": "increase(app_predictions_bucket{le=\"4e+06\"}[3m])",
     "legendFormat": "{le = 4e6}"
    },
    {
     "expr": "increase(app_predictions_bucket{le=\"7e+06\"}[3m])",
     "legendFormat": "{le = 7e6}"
    },
    {
     "expr": "increase(app_predictions_bucket{le=\"1.4e+07\"}[3m])",
     "legendFormat": "{le = 1.4e7}"
    },
    {
     "expr": "increase(app_predictions_bucket{le=\"2.5e+07\"}[3m])",
     "legendFormat": "{le = 2.5e7}"
    },
    {
     "expr": "increase(app_predictions_bucket{le=\"1e+010\"}[3m])",
     "legendFormat": "{le = 1e10}"
    }
   ]
  },
  {
   "title": "Изменение количеста различных запросов к приложению за минуту",
   "type": "bargauge",
   "description": "rate(http_request_size_bytes_count{}[1m])",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_size_bytes_count{}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Длительность обработки запросов приложением",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.05,\r\n    sum(\r\n      rate(\r\n        http_request_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le)\r\n)",
     "legendFormat": "quantile(0.05)"
    },
    {
     "expr": "histogram_quantile(\r\n    0.5,\r\n    sum(\r\n      rate(\r\n        http_request_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le)\r\n)",
     "legendFormat": "quantile(0.5)"
    },
    {
     "expr": "histogram_quantile(\r\n    0.95,\r\n    sum(\r\n      rate(\r\n        http_request_duration_seconds_bucket[1m]\r\n      )\r\n    ) by (le)\r\n)",
     "legendFormat": "quantile(0.95)"
    }
   ]
  },
  {
   "type": "gauge",
   "description": "process_virtual_memory_bytes{}",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes{}", "legendFormat": "__auto" }
   ]
  }
 ]
}